# DataSource Configuration
spring:
  datasource:
    url: jdbc:mysql://172.31.9.81:3306/gym
    username: root
    password: P@ssw0rd123!
    driverClassName: com.mysql.cj.jdbc.Driver
    
  mail:
    host: smtp.gmail.com
    port: 587
    username: sihwork27@gmail.com
    password: csprhtwulrjchpql
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    default-encoding: UTF-8

server:
  tomcat:
    max-threads: 200
  servlet:
    session:
      timeout: 86400s
      cookie:
        max-age: 86400s
  compression:
    enabled: true
    min-response-size: 2048

#spring.datasource.url=jdbc:mysql://localhost:3306/work
#spring.datasource.username=root
#spring.datasource.password=root
#spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver

#
#spring:
#  datasource:
    #url: jdbc:postgresql://aws-0-ap-south-1.pooler.supabase.com:5432/postgres?user=postgres.lmrsqmfavzrbrrjwmgjz&password=${p}
    #username: ${u}
    #password: ${p}
    #driverClassName: org.postgresql.Driver
