# DataSource Configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gym
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver

server:
  tomcat:
    max-threads: 200
  servlet:
    session:
      timeout: 86400s
      cookie:
        max-age: 86400s
  compression:
    enabled: true
    min-response-size: 2048

#spring.datasource.url=jdbc:mysql://localhost:3306/work
#spring.datasource.username=root
#spring.datasource.password=root
#spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver

#
#spring:
#  datasource:
    #url: jdbc:postgresql://aws-0-ap-south-1.pooler.supabase.com:5432/postgres?user=postgres.lmrsqmfavzrbrrjwmgjz&password=${p}
    #username: ${u}
    #password: ${p}
    #driverClassName: org.postgresql.Driver
